##load libraries
library(shiny)
library(shinyjs)
library(shinydashboard)
library(tidyverse)
library(lubridate)
library(leaflet)
library(leaflet.esri)
library(rhandsontable)
library(htmlwidgets)
library(webshot)
library(rmarkdown)
library(knitr)
library(tinytex)
# library(shinymanager)